### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by Echsecutor** [gs1-germany/palletBayCalculator#7]
The webpage demonstrating the functionality of the library is not self-explanatory.

What do I enter where? Where do I see the result? What is the meanin of the numbers?

**Comment by RalphTro** [comment]
Dear @Echsecutor , 

Good point, it may be beneficial to include an illustrative example to better explain how to use th UX.    

Do you also think that I it was beneficial to map the field names with the variable names I used in the javascript code?

**Comment by RalphTro** [comment]
Addressed with https://github.com/gs1-germany/palletBayCalculator/pull/16
